---
components:
  - name: sgm58031
    description: |
      Driver for SGM58031 16-bit I2C ADC
    group: adc-dac
    groups: []
    code_owners: jmpmscorp
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
      - name: esp32s2
      - name: esp32s3
      - name: esp32c3
    licenses:
      - name: ISC
    copyrights:
      - author:
          name: jmpmscorp
        year: 2023
